-- SQLite version of the Oracle database schema
-- Key conversions:
-- - NUMBER → INTEGER or REAL
-- - VARCHAR2 → TEXT
-- - TIMESTAMP → TEXT (ISO 8601 format)
-- - GENERATED BY DEFAULT ON NULL AS IDENTITY → AUTOINCREMENT
-- - CHECK constraints supported natively
-- - Foreign keys must be enabled at runtime: PRAGMA foreign_keys = ON;

PRAGMA foreign_keys = ON;

-- Roles & Users
CREATE TABLE role (
  role_id       INTEGER PRIMARY KEY AUTOINCREMENT,
  name          TEXT NOT NULL UNIQUE
);

CREATE TABLE user_account (
  user_id       TEXT PRIMARY KEY,
  role_id       INTEGER NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  first_name    TEXT NOT NULL,
  last_name     TEXT NOT NULL,
  status        TEXT DEFAULT 'active' CHECK (status IN ('active','suspended')),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES role(role_id)
);

CREATE TABLE student_profile (
  user_id        INTEGER PRIMARY KEY,
  student_number TEXT NOT NULL UNIQUE,
  program_name   TEXT,
  cohort_year    INTEGER,
  FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

CREATE TABLE instructor_profile (
  user_id     INTEGER PRIMARY KEY,
  department  TEXT,
  title       TEXT,
  FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

-- Courses / Sections / Enrollment
CREATE TABLE course (
  course_id     INTEGER PRIMARY KEY AUTOINCREMENT,
  course_code   TEXT NOT NULL,
  course_name   TEXT NOT NULL,
  term          TEXT,
  credit_hours  REAL
);

CREATE TABLE section (
  section_id            INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id             INTEGER NOT NULL,
  section_code          TEXT NOT NULL,
  term                  TEXT,
  primary_instructor_id INTEGER NOT NULL,
  FOREIGN KEY (course_id) REFERENCES course(course_id),
  FOREIGN KEY (primary_instructor_id) REFERENCES user_account(user_id)
);

CREATE TABLE enrollment (
  enrollment_id INTEGER PRIMARY KEY AUTOINCREMENT,
  section_id    INTEGER NOT NULL,
  student_id    INTEGER NOT NULL,
  enrolled_on   DATE DEFAULT CURRENT_DATE,
  status        TEXT DEFAULT 'enrolled' CHECK (status IN ('enrolled','dropped','completed')),
  UNIQUE (section_id, student_id),
  FOREIGN KEY (section_id) REFERENCES section(section_id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

-- Core tracking record
CREATE TABLE time_session (
  session_id     INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id        TEXT NOT NULL,
  session_type   TEXT NOT NULL CHECK (session_type IN ('Class','Study','Clinical')),
  location_text  TEXT,
  section_id     INTEGER,
  clock_in_at    TIMESTAMP NOT NULL,
  clock_out_at   TIMESTAMP,
  duration_minutes INTEGER,
  source         TEXT DEFAULT 'web' CHECK (source IN ('web','mobile','kiosk','admin_edit')),
  status         TEXT DEFAULT 'open' CHECK (status IN ('open','closed','flagged')),
  notes          TEXT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP,
  CHECK ((session_type <> 'Class') OR (section_id IS NOT NULL)),
  FOREIGN KEY (user_id) REFERENCES user_account(user_id),
  FOREIGN KEY (section_id) REFERENCES section(section_id)
);

-- Note: SQLite doesn't support GENERATED ALWAYS AS (computed columns),
-- so duration_minutes is a regular INTEGER. You'll need to calculate it in your application
-- or use a trigger to maintain it.

-- Audit
CREATE TABLE audit_log (
  audit_id      INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_user_id INTEGER NOT NULL,
  target_table  TEXT NOT NULL,
  target_pk     TEXT NOT NULL,
  action        TEXT NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
  before_json   TEXT,
  after_json    TEXT,
  reason        TEXT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_user_id) REFERENCES user_account(user_id)
);

-- Optional permissions
CREATE TABLE permission (
  permission_id INTEGER PRIMARY KEY AUTOINCREMENT,
  code          TEXT NOT NULL UNIQUE,
  description   TEXT
);

CREATE TABLE role_permission (
  role_id       INTEGER NOT NULL,
  permission_id INTEGER NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id) REFERENCES role(role_id),
  FOREIGN KEY (permission_id) REFERENCES permission(permission_id)
);

-- Indexes
CREATE INDEX ix_user_email           ON user_account(email);
CREATE INDEX ix_ts_user_in           ON time_session(user_id, clock_in_at);
CREATE INDEX ix_ts_section_in        ON time_session(section_id, clock_in_at);
CREATE INDEX ix_ts_status            ON time_session(status);
CREATE INDEX ix_ts_location_text     ON time_session(location_text);