alter session set "_oracle_script"=true;

CREATE USER STUDENT_TRACKER IDENTIFIED BY "Strong#Password1"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO STUDENT_TRACKER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO STUDENT_TRACKER;
GRANT UNLIMITED TABLESPACE TO STUDENT_TRACKER;
GRANT EXECUTE ON DBMS_SESSION TO STUDENT_TRACKER;

sqlplus / as sysdba

alter user SYSTEM identified by "VulkanLives"